wczytywanie treningów z bazy/dodanie nazwy treningu oraz jej edycji/usuwanie treningów
CzaplaPL/GitToBeFit-klient pull request #23
Opened 2021-03-29 15:09 UTC by kubaturlej

2021-03-29 15:33 UTC, CzaplaPL requested changes

2021-03-29 15:33 UTC, CzaplaPL commented on app/src/main/java/pl/gittobefit/WorkoutDisplay/dialog/DeleteTrainingDialog.java
> +                    }
czym jest sc1 i dlaczego znowu poszedłeś w strone flagi -999

2021-03-29 15:33 UTC, CzaplaPL commented on app/src/main/java/pl/gittobefit/WorkoutDisplay/dialog/DeleteTrainingDialog.java
> +                    UserTrainings.getInstance().getTrainingArrayList().remove(sc1);
dalej użuywamy singletona ?

2021-03-29 15:33 UTC, CzaplaPL commented on app/src/main/java/pl/gittobefit/WorkoutDisplay/dialog/EditTrainingNameDialog.java
> +                    }
to samo co w usuwaniu

2021-03-29 15:33 UTC, CzaplaPL commented on app/src/main/res/navigation/nav_graph.xml
> +        android:label="EditTrainingName" >
nazwa po angielsku

2021-03-29 15:33 UTC, CzaplaPL commented on app/src/main/res/navigation/nav_graph.xml
> +        android:label="DeleteTrainingName" >
nazwa po angielsku

2021-03-29 15:33 UTC, CzaplaPL commented on app/src/main/res/layout/layout_edit_training_name_dialog.xml
> +        android:hint="Nowa nazwa treningu"
nie w xml

2021-03-29 15:33 UTC, CzaplaPL commented on app/src/main/java/pl/gittobefit/database/entity/training/WorkoutForm.java
> +
?

2021-03-29 15:33 UTC, CzaplaPL commented on app/src/main/java/pl/gittobefit/WorkoutDisplay/fragments/ListOfTrainings.java
>          recyclerView.setLayoutManager(new LinearLayoutManager(getContext(), LinearLayoutManager.VERTICAL, false));
dlaczego jednak nie korzystasz z viewmodel ?

2021-03-29 15:33 UTC, CzaplaPL commented on app/src/main/java/pl/gittobefit/database/entity/training/SavedTraining.java
> +        this.trainingName = "Default training name";
czemu po angielsku

2021-03-29 15:33 UTC, CzaplaPL commented on app/src/main/java/pl/gittobefit/network/WorkoutFormsServices.java
> +        body.setTrainingName("Default training name");
czemu po angielsku

2021-03-29 17:26 UTC, KacperCzajkowski approved these changes
Parę poprawek dla czystości kody, ale poza tym okej

2021-03-29 17:26 UTC, KacperCzajkowski commented on app/src/main/java/pl/gittobefit/WorkoutDisplay/fragments/DisplayReceivedTraining.java
> +            SavedTraining savedTraining = AppDataBase.getInstance(getContext()).training().getOneTraining(result2.get(index).getId());
Wydaje mi się że ``` AppDataBase.getInstance(getContext()) ``` moze być zmienną oddzielną

2021-03-29 17:26 UTC, KacperCzajkowski commented on app/src/main/java/pl/gittobefit/WorkoutDisplay/fragments/ListOfTrainings.java
> +            List<SavedTraining> result2 = AppDataBase.getInstance(getContext()).training().getInfoForTrainingList();
Jak wyżej

2021-03-29 17:26 UTC, KacperCzajkowski commented on app/src/main/java/pl/gittobefit/database/dao/IExerciseDao.java
> +
```suggestion
```

2021-04-06 05:50 UTC, CzaplaPL commented on app/src/main/java/pl/gittobefit/WorkoutDisplay/dialog/DeleteTrainingDialog.java
> +                    AppDataBase.getInstance(getContext()).workoutForm().deleteFormInDataBase(Integer.parseInt(tokens[1]));
wystawił bym jakas funkcje w repozytorium i tu wykonał jedno wywolanie a w nim te dwa

2021-04-06 05:50 UTC, CzaplaPL commented on app/src/main/java/pl/gittobefit/WorkoutDisplay/dialog/EditExerciseDialog.java
> +        countNumberPicker.setOnValueChangedListener(this);
nie mozna czesci przeniesc do xml

2021-04-06 05:50 UTC, CzaplaPL commented on app/src/main/java/pl/gittobefit/WorkoutDisplay/dialog/EditExerciseDialog.java
> +                    System.out.println(seriesNumberPicker.getValue() + " " + countNumberPicker.getValue());
nie wiem czy na produkcji nie powinno byc logowania w logcat ale do sprawa do zastanowienia sie na spotkaniu

2021-04-06 12:13 UTC, KacperCzajkowski reviewed
Czekam na argumentację stosowania singletonów. Zwłaszcza, że niżej jest stosowane już repozytorium

2021-04-06 12:13 UTC, KacperCzajkowski commented on app/src/main/java/pl/gittobefit/WorkoutDisplay/dialog/EditTrainingNameDialog.java
> +                    UserTrainings.getInstance().getTraining(Integer.parseInt(tokens[0])).setTrainingName(newTrainingName);
Jak wyżej

2021-04-06 12:13 UTC, KacperCzajkowski commented on app/src/main/java/pl/gittobefit/WorkoutDisplay/fragments/DisplayReceivedTraining.java
> +        List<SavedTraining> result2 = AppDataBase.getInstance(getContext()).training().getInfoForTrainingList();
```suggestion
        List<SavedTraining> savedTrainings = AppDataBase.getInstance(getContext()).training().getInfoForTrainingList();
```

2021-04-06 12:13 UTC, KacperCzajkowski commented on app/src/main/java/pl/gittobefit/WorkoutDisplay/fragments/DisplayReceivedTraining.java
> +        if (index != UserTrainings.getInstance().getTrainingArrayList().size() && UserTrainings.getInstance().getTraining(index).getPlanList().size() == 0) {
Podwójne zastosowanie singletona (sprawa jak wyżej) plus mocno długi warunek, który mógłby być wydzielony do innej metody prywatnej

2021-04-06 12:13 UTC, KacperCzajkowski commented on app/src/main/java/pl/gittobefit/WorkoutDisplay/fragments/DisplayReceivedTraining.java
> +            SavedTraining savedTraining = AppDataBase.getInstance(getContext()).training().getOneTraining(result2.get(index).getId());
Jeżeli dobrze to rozumiem, to w liście ```result2``` powinieneś mieć ten trening i wtedy nie trzeba by było pobierać go z bazy

2021-04-06 12:13 UTC, KacperCzajkowski commented on app/src/main/java/pl/gittobefit/WorkoutDisplay/fragments/DisplayReceivedTraining.java
> +        }
Wydaje mi się, że jakbyś korzystał z repozytorium wystawionego przez Dominika, to nie trzeba by było ręcznie mapować. (Jeżeli nie będziesz chciał z niego korzystać, to może lepiej jest to wydzielić do metody prywatnej)

2021-04-06 12:13 UTC, KacperCzajkowski commented on app/src/main/java/pl/gittobefit/WorkoutDisplay/fragments/DisplayReceivedTraining.java
> +                        buttonArrayList.get(i).setVisibility(View.VISIBLE);
Wielokrotne powtórzenie ```UserTrainings.getInstance()```

2021-04-06 19:28 UTC, CzaplaPL commented on app/src/main/java/pl/gittobefit/WorkoutDisplay/dialog/DeleteTrainingDialog.java
> +                    AppDataBase.getInstance(getContext()).workoutForm().deleteFormInDataBase(Integer.parseInt(tokens[1]));
świetny pomysł

2021-04-06 19:28 UTC, CzaplaPL commented on app/src/main/java/pl/gittobefit/WorkoutDisplay/dialog/DeleteTrainingDialog.java
> +                    AppDataBase.getInstance(getContext()).workoutForm().deleteFormInDataBase(Integer.parseInt(tokens[1]));
świetny pomysł

2021-04-07 14:41 UTC, CzaplaPL commented on app/src/main/java/pl/gittobefit/HomeFragment.java
> +        }
dlaczego robisz to w homefragment 
pamietaj ze po zalogowaniu w 2 watku sa pobierane treningi z serwera i w user jest specjalny enum mowiacy o tym

2021-04-07 14:41 UTC, CzaplaPL commented on app/src/main/java/pl/gittobefit/WorkoutDisplay/adapters/ExerciseListAdapter.java
> +    public ExerciseListAdapter(ArrayList<Exercise> exerciseArrayList, ArrayList<ExerciseExecutionPOJODB> exercisesExecutionArrayList, String scheduleType, int trainingID, Fragment fragment) {
połam linie

2021-04-08 13:54 UTC, CzaplaPL approved these changes

2021-04-12 17:32 UTC, CzaplaPL commented on app/src/main/java/pl/gittobefit/WorkoutDisplay/adapters/ExerciseListAdapter.java
> +        if (exercisesExecutionArrayList.get(position).getTime() > 20)
nie jestem pewnien czy to dobry warunek wydaje mi sie ze powinismy porownywac liczbe powtórzen rozna od zera

2021-04-12 17:32 UTC, CzaplaPL commented on app/src/main/java/pl/gittobefit/WorkoutDisplay/adapters/ExerciseListAdapter.java
> +            if (scheduleType.equals("CIRCUIT"))
wydaje mi sie ze pierwszy if powinien byc własnie odnosnie obwodow wtedy moglbys te swiche wrzucic w warunki i nie zawsze by sie wykonywały

2021-04-12 17:32 UTC, CzaplaPL commented on app/src/main/java/pl/gittobefit/WorkoutDisplay/adapters/ExerciseListAdapter.java
> +            editExerciseDialog.show(fragment.getFragmentManager(), "dialog");
get fragment menager jest deprecated 
chyba p[owinna byc tu nawigacja ?

2021-04-12 17:32 UTC, CzaplaPL commented on app/src/main/java/pl/gittobefit/WorkoutDisplay/dialog/DeleteTrainingDialog.java
> +                    AppDataBase.getInstance(getContext()).workoutFormDao().deleteFormInDataBase(Integer.parseInt(tokens[1]));
moze zrobic pod to jakas funkcje  w repozytorium ?

2021-04-12 17:32 UTC, CzaplaPL commented on app/src/main/java/pl/gittobefit/WorkoutDisplay/dialog/EditExerciseDialog.java
> +        this.exerciseExecutionPOJODBS = exerciseExecutionPOJODBS;
moze tutaj tez podpiac model ?

2021-04-12 17:32 UTC, CzaplaPL commented on app/src/main/java/pl/gittobefit/WorkoutDisplay/dialog/EditExerciseDialog.java
> +            countNumberPicker.setMinValue(10);
warunek chyba nie taki sam tutaj pozwalasz zeby cwiczenie trwalo 10 sekund a sprawdzasz dla 20 
nwm tez czy 90 sekund to nie za mało mogą być cwiczenia jak bieg na biezni ktore ktos moglby chciec robic dłuzej ale to zobaczymy co chlopaki powiedza

2021-04-12 17:32 UTC, CzaplaPL commented on app/src/main/java/pl/gittobefit/WorkoutDisplay/dialog/EditExerciseDialog.java
> +        }
wyzej sprawdzasz juz ten warunek i moglbys ten tekst ustawiac tam

2021-04-12 17:32 UTC, CzaplaPL commented on app/src/main/java/pl/gittobefit/WorkoutDisplay/dialog/EditExerciseDialog.java
> +        InitiationTrainingDisplayLayoutViewModel model = new ViewModelProvider(requireActivity()).get(InitiationTrainingDisplayLayoutViewModel.class);
dlaczego wczesniej nie korzystales z modelu ?

2021-04-12 17:32 UTC, CzaplaPL commented on app/src/main/java/pl/gittobefit/WorkoutDisplay/dialog/EditExerciseDialog.java
> +                .setNegativeButton(getString(R.string.admit_changes), (dialog, which) ->
dajac jako negatywny buuton zatwierdz utrudniamy niezapisanie zmian

2021-04-12 17:32 UTC, CzaplaPL commented on app/src/main/java/pl/gittobefit/WorkoutDisplay/dialog/EditExerciseDialog.java
> +                .setPositiveButton(getString(R.string.change_exercise), (dialog, which) ->
moze pod to dac jakis przycisk w layaucie

2021-04-12 17:32 UTC, CzaplaPL commented on app/src/main/java/pl/gittobefit/WorkoutDisplay/dialog/EditExerciseDialog.java
> +                            model.getCurrentSeries().setValue(seriesNumberPicker.getValue());
dlaczego robisz to w modelu i robisz to tutaj wydaje sie ze najlatwiej byloby to robic w modelu ktory by automatycznie tez przez repozytorium zapisywal to w bazie

2021-04-12 17:32 UTC, CzaplaPL commented on app/src/main/java/pl/gittobefit/WorkoutDisplay/dialog/EditExerciseDialog.java
> +                        model.getCurrentSeries().setValue(seriesNumberPicker.getValue());
jw

2021-04-12 17:32 UTC, CzaplaPL commented on app/src/main/java/pl/gittobefit/WorkoutDisplay/dialog/EditExerciseDialog.java
> +                    if (exercisesExecutionArrayList.get(position).getTime() > 20)
warunek

2021-04-12 17:32 UTC, CzaplaPL commented on app/src/main/java/pl/gittobefit/WorkoutDisplay/dialog/EditTrainingNameDialog.java
> +                    AppDataBase.getInstance(getContext()).trainingDao().updateTrainingNameInDataBase(newTrainingName, Integer.parseInt(tokens[1]));
moze jakas funkcja w modelu ktora by to robila

2021-04-12 17:32 UTC, CzaplaPL commented on app/src/main/res/navigation/nav_graph.xml
> +            app:popUpToInclusive="true"/>
nie powinien z tad wracac do homa ?

2021-04-12 17:32 UTC, CzaplaPL commented on app/src/main/res/drawable/plus_minus_anim.xml
> +</animation-list>
pod animacje jest osobny folder

2021-04-12 17:32 UTC, CzaplaPL commented on app/src/main/res/navigation/nav_graph.xml
> +            app:popUpToInclusive="true"/>
nie powino stad wracac do home ?

2021-04-12 17:33 UTC, CzaplaPL commented on app/src/main/res/drawable/plus_minus_anim.xml
> +</animation-list>
do animacji jest osobny folder

2021-04-12 18:20 UTC, CzaplaPL approved these changes
jest git

2021-04-12 18:20 UTC, CzaplaPL commented on app/src/main/java/pl/gittobefit/WorkoutDisplay/fragments/DisplayReceivedTraining.java
> +        }
co to robi ?

2021-04-12 18:20 UTC, CzaplaPL commented on app/src/main/java/pl/gittobefit/WorkoutDisplay/fragments/DisplayReceivedTraining.java
> +            editTrainingNameDialog.show(getFragmentManager(), "dialog");
deprecated

2021-04-12 18:20 UTC, CzaplaPL commented on app/src/main/java/pl/gittobefit/WorkoutDisplay/fragments/DisplayReceivedTraining.java
> +            deleteTrainingDialog.show(getFragmentManager(), "dialog");
jw

2021-04-12 18:20 UTC, CzaplaPL commented on app/src/main/java/pl/gittobefit/WorkoutDisplay/viewmodel/InitiationTrainingDisplayLayoutViewModel.java
> +        }
states = new ArrayList(count ) ale to chlopakow od javy trzeba było by sie dopytac

2021-04-12 18:20 UTC, CzaplaPL commented on app/src/main/java/pl/gittobefit/WorkoutDisplay/fragments/DisplayReceivedTraining.java
>          }
jak nizej

2021-04-12 18:20 UTC, CzaplaPL commented on app/src/main/java/pl/gittobefit/WorkoutDisplay/fragments/DisplayReceivedTraining.java
> +            model.setState(2);
lisnery wyrzucił bym do oncreate troche to poprawiło by czytelnosc

2021-04-12 18:20 UTC, CzaplaPL commented on app/src/main/java/pl/gittobefit/WorkoutDisplay/fragments/DisplayReceivedTraining.java
> +                    if (trainingWithForm.form.getTrainingType().equals("FBW") || trainingWithForm.form.getTrainingType().equals("SPLIT")) {
dlaczego w tych typach ?

2021-04-12 18:20 UTC, CzaplaPL commented on app/src/main/java/pl/gittobefit/WorkoutDisplay/fragments/DisplayReceivedTraining.java
> +        final Observer<Integer> exerciseInfoObserver = new Observer<Integer>() {
nie wiem czy to dobrze ze podczas zmiany jednego cwiczenia przeładowuja sie wszystkie listy

2021-04-12 20:53 UTC, KacperCzajkowski approved these changes

2021-04-12 20:53 UTC, KacperCzajkowski commented on app/src/main/java/pl/gittobefit/WorkoutDisplay/adapters/ExerciseListAdapter.java
> +                               String scheduleType, int trainingID, Fragment fragment, ArrayList<ArrayList<ExerciseExecutionPOJODB>> exerciseExecutionPOJODBS) {
Na moje to bym połamał tak, że w każdej linii masz jeden parametr

2021-04-12 20:53 UTC, KacperCzajkowski commented on app/src/main/java/pl/gittobefit/WorkoutDisplay/adapters/ExerciseListAdapter.java
> +                        properFormCircuit, exercisesExecutionArrayList.get(position).getTime());
Wydaje mi się, że jeżeli mamy dużo parametrów to lepiej zacząć łamać co parametr

2021-04-12 20:53 UTC, KacperCzajkowski commented on app/src/main/java/pl/gittobefit/WorkoutDisplay/adapters/ExerciseListAdapter.java
> +                    exerciseExecutionPOJODBS);
Propozycja łamania linii jak wyżej

2021-04-12 20:53 UTC, KacperCzajkowski commented on app/src/main/java/pl/gittobefit/WorkoutDisplay/dialog/EditExerciseDialog.java
> +                              int trainingID, String exerciseName, ArrayList<ArrayList<ExerciseExecutionPOJODB>> exerciseExecutionPOJODBS)
Łamanie JW

2021-04-12 20:53 UTC, KacperCzajkowski commented on app/src/main/java/pl/gittobefit/WorkoutDisplay/fragments/DisplayReceivedTraining.java
> +            exercisesArrayList.add(TrainingRepository.getInstance(getContext()).getExerciseForPlanList(trainingWithForm.training.getPlanList().get(i)));
Dałoby radę to jakoś rozbić? Ta linia wygląda trochę potężnie

2021-04-12 20:53 UTC, KacperCzajkowski commented on app/src/main/java/pl/gittobefit/WorkoutDisplay/fragments/DisplayReceivedTraining.java
> +                            trainingWithForm.form.getScheduleType(), trainingWithForm.training.getId(), getParentFragment(), trainingWithForm.training.getPlanList()));
Łamanie JW

2021-04-12 20:53 UTC, KacperCzajkowski commented on app/src/main/java/pl/gittobefit/WorkoutDisplay/fragments/DisplayReceivedTraining.java
> +    private void changePlusToMinus(Button day1Button, int p) {
Może jakaś inna nazwa dla tego buttona?

2021-04-12 20:53 UTC, KacperCzajkowski commented on app/src/main/java/pl/gittobefit/WorkoutDisplay/viewmodel/InitiationTrainingDisplayLayoutViewModel.java
> +        }
Omawiane na code review. Link: https://www.javatpoint.com/java-collections-fill-method

2021-04-14 17:03 UTC, merged